<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Product Label
 */
/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $element */
?>
<?php $element = $block->getElement() ?>
<?php $jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $element->getHtmlId() ?>
<div class="rule-tree">
    <fieldset id="<?= $block->escapeHtmlAttr($jsObjectName) ?>" <?= /* @noEscape */ $element->serialize(['class']) ?> class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml($element->getLegend()) ?></span></legend>
        <br>
    <?php if ($element->getComment()) : ?>
        <div class="messages">
            <div class="message message-notice"><?= $block->escapeHtml($element->getComment()) ?></div>
        </div>
    <?php endif; ?>
    <div class="rule-tree-wrapper">
        <?= $element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?= /* @noEscape */ $jsObjectName ?> = new VarienRulesForm('<?= /* @noEscape */ $jsObjectName ?>', '<?= /* @noEscape */ $block->getNewChildUrl() ?>');
<?php if ($element->getReadonly()) : ?>
    <?= /* @noEscape */ $element->getHtmlId() ?>.setReadonly(true);
<?php endif; ?>

});
</script>
